export const fallbackTeam = [
  {
    _id: '1',
    name: 'Tejas Pawar',
    role: 'CEO',
    image: '/team/tejas_pawar.jpeg',
    linkedin: 'https://www.linkedin.com/in/tejas-pawar-theLazyWolf/',
    order: 1,
  },
  {
    _id: '2',
    name: 'Arnav Tripathi',
    role: 'CFO Head & Marketing Head',
    image: '/team/arnav_tripathi.jpeg',
    linkedin: 'https://www.linkedin.com/in/arnav-tripathi-174150197',
    order: 2,
  },
  {
    _id: '3',
    name: 'Soham Dugade',
    role: 'Networking Head',
    image: '/team/soham_dugade.jpeg',
    linkedin: 'https://www.linkedin.com/in/soham-dugade-364520332/',
    order: 3,
  },
  {
    _id: '4',
    name: 'Ved Songire',
    role: 'CTO & Documentation Head',
    image: '/team/ved_songire.jpeg',
    linkedin: 'https://www.linkedin.com/in/ved-songire-768a9a32a/',
    order: 4,
  },
  {
    _id: '5',
    name: 'Kedar Sawant',
    role: 'CTO Head',
    image: '/team/kedar_sawant.jpeg',
    linkedin: 'https://www.linkedin.com/in/kedar-sawant-891968340/',
    order: 5,
  },
  {
    _id: '6',
    name: 'Pakhi Katre',
    role: 'CFO Co-Head',
    image: '/team/pakhi_katre.png',
    linkedin: 'https://www.linkedin.com/in/pakhi-katre-563536284/',
    order: 6,
  },
];

export const fallbackEvents = [
  {
    _id: 'e1',
    title: 'Startup Spark 2026',
    description: 'An intensive 48-hour hackathon where aspiring entrepreneurs build MVPs from scratch. Pitch to real investors, win seed funding, and launch your startup journey.',
    date: '2026-05-15T00:00:00.000Z',
    location: 'Vidyalankar Institute of Technology, Wadala, Mumbai',
    category: 'hackathon',
    isUpcoming: true,
  },
  {
    _id: 'e2',
    title: 'Ideathon: Think Beyond',
    description: 'Present your innovative business ideas to a panel of industry veterans and VCs. Top 3 ideas receive mentorship and incubation support.',
    date: '2026-06-10T00:00:00.000Z',
    location: 'VIT Seminar Hall, Mumbai',
    category: 'competition',
    isUpcoming: true,
  },
  {
    _id: 'e3',
    title: 'Workshop: Building Scalable Products',
    description: 'Learn how to take your product from 0 to 1 with expert-led sessions on lean methodology, user research, and technical architecture.',
    date: '2026-04-20T00:00:00.000Z',
    location: 'VIT Computer Lab, Mumbai',
    category: 'workshop',
    isUpcoming: true,
  },
  {
    _id: 'e4',
    title: 'Entrepreneurship Conclave 2025',
    description: 'Our flagship annual event featuring keynotes from founders of unicorn startups, panel discussions on funding, and networking sessions.',
    date: '2025-12-05T00:00:00.000Z',
    location: 'VIT Auditorium, Mumbai',
    category: 'seminar',
    isUpcoming: false,
  },
  {
    _id: 'e5',
    title: 'Pitch Perfect',
    description: 'A shark-tank style event where student founders pitch their startups to angel investors and successful entrepreneurs.',
    date: '2025-10-22T00:00:00.000Z',
    location: 'VIT Seminar Hall, Mumbai',
    category: 'competition',
    isUpcoming: false,
  },
  {
    _id: 'e6',
    title: 'FinTech Workshop',
    description: 'Hands-on workshop on building fintech products, understanding regulatory compliance, and leveraging UPI/blockchain technology.',
    date: '2025-09-14T00:00:00.000Z',
    location: 'VIT Computer Lab, Mumbai',
    category: 'workshop',
    isUpcoming: false,
  },
];
